Fix observer.getAutomationTimeScheduledTasks
OAK-Foundation/OAK-JS-SDK pull request #23
Opened 2022-10-25 15:10 UTC by imstar15

2022-10-25 15:17 UTC, chrisli30 requested changes

2022-10-25 15:17 UTC, chrisli30 commented on test/functional/helpFn.ts
> +   expect(_.find(tasks, (task) => !_.isNil(_.find(task, ([_account, scheduledTaskId]) => scheduledTaskId === taskID)))).toBeUndefined();
Applies to all _.find below.

2022-10-26 02:19 UTC, imstar15 commented on test/functional/helpFn.ts
> +   expect(_.find(tasks, (task) => !_.isNil(_.find(task, ([_account, scheduledTaskId]) => scheduledTaskId === taskID)))).toBeUndefined();
Fixed.

The tasks structure like this:
```
tasks: [
    [
      68PSWTqBNEDRdVzwGfKqzubY6hTj4Zef98gG93sC5XhtefuG
      0x016b319a55b452dce062db93043c412f03e74dbe313ed00a4f2afb729a8b3a5b
    ]
    [
      68PSWTqBNEDRdVzwGfKqzubY6hTj4Zef98gG93sC5XhtefuG
      0x96c34ed205064d8b09035ae284571c21d29aef9da0da01dd8d46b3d2e55e372b
    ]
    [
      67ykuCNocYBxBeEymRJ7AzFbEVX2Rx1S22Q5KnrsBwRTTdWM
      0xce33f49a6894f10c1b3c3d75bcfd62f57fb84705a70dbe028edfa2e9a68642fc
    ]
    [
      67ykuCNocYBxBeEymRJ7AzFbEVX2Rx1S22Q5KnrsBwRTTdWM
      0x5a84f54e8cca120ecfd2edcc3ecf1183fd0f1efdd30e4c265e649eb3ee29d9a3
    ]
    [
      67ykuCNocYBxBeEymRJ7AzFbEVX2Rx1S22Q5KnrsBwRTTdWM
      0x9d3833de3787c6271c9c1c78b97a86e32b0268a60f1207686e4976c79c54a66c
    ]
  ]
```

2022-10-27 05:22 UTC, chrisli30 approved these changes
Yes this is more readable now. Please keep the standard.

2022-10-27 15:43 UTC, merged